robomaster_test_node:
  ros__parameters:
    upperRight: 1
    upperLeft: 2
    lowwerLeft: 3
    lowerRight: 4
    urGainKP: 3.14
    urGainKI: 3.14
    urGainKD: 3.14
    ulGainKP: 3.14
    ulGainKI: 3.14
    ulGainKD: 3.14
    llGainKP: 3.14
    llGainKI: 3.14
    llGainKD: 3.14
    lrGainKP: 3.14
    lrGainKI: 3.14
    lrGainKD: 3.14